version: '2'
services:
  corp-vol:
    build: volume-db
    volumes:
      - ./code:/var/www/htdocs
#      - ./code:/var/www/html
  corp-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hris
      - MYSQL_USER=administrator
      - MYSQL_PASSWORD=pass123
    volumes:
      - corp-db-data:/var/lib/mysql
    networks:
      - back-tier
  web:
    build: hris-web
    links:
      - corp-db
    volumes_from:
      - corp-vol
    networks:
      - back-tier
  corp:
    build: docker-drupal-php53-dev-master
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - corp-vol
    links:
      - corp-db
    networks:
      - back-tier
      - front-tier
volumes:
  corp-db-data:
    driver: local
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

